# Generated by Django 4.2.3 on 2023-07-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_audio_created_at_audio_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
