# Generated by Django 4.2.3 on 2023-07-23 03:24

from django.db import migrations, models
import django.db.models.deletion

def move_files(apps, schema_editor):
    Audio = apps.get_model('api', 'Audio')
    AudioFile = apps.get_model('api', 'AudioFile')
    for audio in Audio.objects.all():
        file = AudioFile(file=audio.file, audio=audio, notes="")
        file.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_audio_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('notes', models.TextField()),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.audio')),
            ],
        ),
        migrations.RunPython(move_files),
        migrations.RemoveField(
            model_name='audio',
            name='file',
        ),
    ]
